# Setup
title:            Hyde
tagline:          'Marcelo J. Moglie'
description:      'A Postdoc at <a href="https://www.crick.ac.uk/" target="_blank">The Francis Crick Institute</a>'
url:              https://marcelo-moglie.github.io/web
baseurl:          'https://marcelo-moglie.github.io/web'
paginate:         5

# About and contact
author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0
